const wordRusText = document.querySelectorAll('.word__rus-text');

let lesson1Rus = [
	"Я работаю",
	"Мы работаем",
	"Они работают",
	"Ты работаешь",
	"Я работаю здесь",
	"Я учусь",
	"Я понимаю",
	"Я понимаю тебя",
	"Я знаю это",
	"Я знаю это очень хорошо",
	"Я живу в России",
	"Я говорю по-английски",
	"Я хожу в школу",
	"Я хожу на работу",
	"У меня есть брат",
	"У меня есть идея",
	"У меня есть сестра",
	"У меня есть машина",
	"Я думаю так",
	"Я вижу это",
	"Мне нужно это",
	"Я помню это",
	"Я помню это очень хорошо",
	"Мы понимаем тебя",
	"Мы говорим по-английски",
	"Ты знаешь это",
	"Ты видишь это",
	"Они помогают мне",
	"Они идут на работу",
	"Мы помним это",
	"Ты говоришь по-английски очень хорошо",
	"Мы живём здесь",
	"Я живу в этом городе",
	"Мы живём в этой стране",
]

const wordEngText = document.querySelectorAll('.word__eng-text');

let lesson1Eng = [
	"I work",
	"We work",
	"They work",
	"You work",
	"I work here",
	"I study",
	"I understand",
	"I understand you",
	"I know it",
	"I know it wery well",
	"I live in Russia",
	"I speak English",
	"I go to school",
	"I go to work",
	"I have a brother",
	"I have an idea",
	"I have a sister",
	"I have a car",
	"I think so",
	"I see it",
	"I want it",
	"I remember it",
	"I remember it very well",
	"We understand you",
	"We speak English",
	"I know it",
	"You see it",
	"They help me",
	"They go to work",
	"We remember it",
	"You speak English very well",
	"We leave here",
	"I leave in this city",
	"We leave in this country",
]

	for (let i = 0; i < wordRusText.length; i++) {
		wordRusText[i].textContent = lesson1Rus[i];
		wordEngText[i].textContent = lesson1Eng[i];
	}